### ISSUE TITLE
Can you publish to NPM?

### ISSUE THREAD

**Issue by simon-p-r** [thunder9/node-dde#3]
Hi

Can you please publish this to the NPM repo?  

Thanks
Simon

**Comment by simon-p-r** [comment]
Closed as published my fork to npm

**Comment by thunder9** [comment]
Hi,

I've made some changes to the module, so I would like to publish new version to the npm.
Can you add my account to the `node-dde` package using `npm owner add thunder9 node-dde`?

**Comment by simon-p-r** [comment]
Maybe best if I unpublished module first and then you can publish as the owner.

**Comment by thunder9** [comment]
That sounds good to me.
Sorry to trouble you,  could you unpublish the moulde?

**Comment by simon-p-r** [comment]
I have unpublished so you are free to publish your module now.

**Comment by thunder9** [comment]
Thank you. I'v published.
