### ISSUE TITLE
Multi-threading

### ISSUE THREAD

**Issue by simon-p-r** [thunder9/node-dde#6]
Hello again

I believe the c# library used by edge supports multi-threading but I don't either know c# or what the api is. I am wondering whether this is supported by this module? My use case is some c# multi-threading code is calling a legacy DDE server via this module and I cannot seem to get it to work.

**Comment by thunder9** [comment]
Hello

In the current version, the client (via `dde.createClinet`) is assumed to be created only one at the same time.

**Comment by simon-p-r** [comment]
Sorry the nnde library allows for synchronization of threads but I cannot see if I can use this with your module.  If I understand you correctly each client I create can talk to the same dde-server as long as I create a new client for each interaction.
